SELECT U.NAME AS "USUARIO",
	V.TITLE AS "TÍTULO",
	COUNT(1) AS "QUANTIDADE DE VEZES QUE ASSISTIU"
FROM MOVIE_DB.WATCHED_TITLE WT
INNER JOIN MOVIE_DB.USERS U ON WT.USER_ID = U.USER_ID
INNER JOIN MOVIE_DB.VIDEOS V ON WT.VIDEO_ID = V.VIDEO_ID
GROUP BY U.NAME,
	V.TITLE