-- For tests
--INSERT INTO MOVIE_DB.PLANS (qtt_screens, price) values (1, 9.90);
--INSERT INTO MOVIE_DB.PLANS (qtt_screens, price) values (2, 14.90);
--INSERT INTO MOVIE_DB.PLANS (qtt_screens, price) values (3, 18.90);
--INSERT INTO MOVIE_DB.PLANS (qtt_screens, price) values (4, 22.90);

--SELECT * FROM MOVIE_DB.PLANS ORDER BY PLAN_ID

--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 1, 'user 1', CURRENT_DATE, 'mail 1', 'pass 1', TRUE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 2, 'user 2', CURRENT_DATE, 'mail 2', 'pass 2', TRUE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 3, 'user 3', CURRENT_DATE, 'mail 3', 'pass 3', TRUE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 4, 'user 4', CURRENT_DATE, 'mail 4', 'pass 4', TRUE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 4, 'user 5', CURRENT_DATE, 'mail 5', 'pass 5', FALSE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (7, 4, 'user 6', CURRENT_DATE, 'mail 6', 'pass 6', TRUE);

--SELECT * FROM MOVIE_DB.USERS

SELECT U.PLAN_ID AS "IDENTIFICADOR DO PLANO", COUNT(1) AS "QUANTIDADE ASSINANTES" FROM MOVIE_DB.USERS U INNER JOIN MOVIE_DB.PLANS P ON U.PLAN_ID = P.PLAN_ID WHERE U.PLAN_ACTIVE = TRUE GROUP BY U.PLAN_ID