--INSERT INTO MOVIE_DB.PLANS (QTT_SCREENS, PRICE) VALUES (1, 9.90);
--SELECT * FROM MOVIE_DB.PLANS

--INSERT INTO MOVIE_DB.COUNTRIES (TOP_LEVEL_DOMAIN) VALUES ('BR');
--SELECT * FROM MOVIE_DB.COUNTRIES

--INSERT INTO MOVIE_DB.LANGUAGES (NAME, COUNTRY_ID) VALUES ('Português - BR', 1);
--SELECT * FROM MOVIE_DB.LANGUAGES

--INSERT INTO MOVIE_DB.AUDIOS (LANGUAGE_ID, NAME) VALUES (1, 'Português - BR');
--SELECT * FROM MOVIE_DB.AUDIOS

--INSERT INTO MOVIE_DB.SUBTITLES (LANGUAGE_ID, NAME) VALUES (1, 'Português - BR');
--SELECT * FROM MOVIE_DB.SUBTITLES

--INSERT INTO MOVIE_DB.USER_PREFERENCES (AUDIO_ID, SUBTITLE_ID, LANGUAGE_ID) VALUES (1, 1, 1);
--SELECT * FROM MOVIE_DB.USER_PREFERENCES

--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (1, 1, 'USER 1', CURRENT_DATE, 'MAIL', 'PASSWORD', TRUE);
--INSERT INTO MOVIE_DB.USERS (PREFERENCES_ID, PLAN_ID, NAME, BIRTH_DATE, EMAIL, PASSWORD, PLAN_ACTIVE) VALUES (1, 1, 'USER 2', CURRENT_DATE, 'MAIL', 'PASSWORD', TRUE);
--SELECT * FROM MOVIE_DB.USERS

--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 178, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: As Duas Torres', 179, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: O Retorno do Rei', 223, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('Titanic', 194, TRUE);

--INSERT INTO MOVIE_DB.CONTINUE_WATCHING (REMAINING_TIME, USER_ID, VIDEO_ID) VALUES (20, 1, 1);
--INSERT INTO MOVIE_DB.CONTINUE_WATCHING (REMAINING_TIME, USER_ID, VIDEO_ID) VALUES (25, 1, 2);
--INSERT INTO MOVIE_DB.CONTINUE_WATCHING (REMAINING_TIME, USER_ID, VIDEO_ID) VALUES (105, 1, 3);
--INSERT INTO MOVIE_DB.CONTINUE_WATCHING (REMAINING_TIME, USER_ID, VIDEO_ID) VALUES (52, 2, 2);
--INSERT INTO MOVIE_DB.CONTINUE_WATCHING (REMAINING_TIME, USER_ID, VIDEO_ID) VALUES (41, 2, 4);

--SELECT * FROM MOVIE_DB.CONTINUE_WATCHING

SELECT U.NAME AS "Usuário",
	V.TITLE AS "Título",
    WL.REMAINING_TIME AS "Tempo restante"
FROM MOVIE_DB.CONTINUE_WATCHING WL
INNER JOIN MOVIE_DB.VIDEOS V ON WL.VIDEO_ID = V.VIDEO_ID
INNER JOIN MOVIE_DB.USERS U ON WL.USER_ID = U.USER_ID

