--INSERT INTO MOVIE_DB.COUNTRIES (TOP_LEVEL_DOMAIN) VALUES ('BR');
--INSERT INTO MOVIE_DB.COUNTRIES (TOP_LEVEL_DOMAIN) VALUES ('EN');
--SELECT * FROM MOVIE_DB.COUNTRIES

--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 178, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: As Duas Torres', 179, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('O Senhor dos Anéis: O Retorno do Rei', 223, TRUE);
--INSERT INTO MOVIE_DB.VIDEOS (TITLE, DURATION, PUBLISHED_STATUS) VALUES ('Titanic', 194, TRUE);

--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (1, 1);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (1, 2);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (1, 3);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (1, 4);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (2, 1);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (2, 2);
--INSERT INTO MOVIE_DB.DISTRIBUTION_RULES (COUNTRY_ID, VIDEO_ID) VALUES (2, 3);

SELECT C.TOP_LEVEL_DOMAIN AS "País",
	V.TITLE AS "Título"
FROM MOVIE_DB.DISTRIBUTION_RULES DR
INNER JOIN MOVIE_DB.COUNTRIES C ON DR.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN MOVIE_DB.VIDEOS V ON DR.VIDEO_ID = V.VIDEO_ID
WHERE C.TOP_LEVEL_DOMAIN = 'BR'